version: '3.8'

services:
  satisfactory-planner-db:
    image: postgres:16
    container_name: satisfactory-planner-db
    environment:
      POSTGRES_DB: satisfactory-planner
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#
#volumes:
#  postgres_data: